from __future__ import annotations

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]

MANIPULATION_REAL = "real"
MANIPULATION_DF = "df"
MANIPULATION_NT = "nt"
MANIPULATION_TYPES = (MANIPULATION_REAL, MANIPULATION_DF, MANIPULATION_NT)
FAKE_MANIPULATION_TYPES = (MANIPULATION_DF, MANIPULATION_NT)

SPLIT_TRAIN = "train"
SPLIT_VAL = "val"
SPLIT_TEST = "test"
SPLIT_NAMES = (SPLIT_TRAIN, SPLIT_VAL, SPLIT_TEST)

TASK_DF_VS_REAL = "mobilenetv2_df_vs_real"
TASK_NT_VS_REAL = "mobilenetv2_nt_vs_real"
TASK_IDS = (TASK_DF_VS_REAL, TASK_NT_VS_REAL)

TASK_TO_FAKE_CLASS = {
    TASK_DF_VS_REAL: MANIPULATION_DF,
    TASK_NT_VS_REAL: MANIPULATION_NT,
}

QUANT_FP32_GPU = "fp32_gpu"
QUANT_DYNAMIC_RANGE = "dynamic_range_tflite"
QUANT_INT8_STATIC = "int8_static_tflite"
QUANT_FLOAT16 = "float16_tflite"
QUANTIZATION_IDS = (
    QUANT_FP32_GPU,
    QUANT_DYNAMIC_RANGE,
    QUANT_INT8_STATIC,
    QUANT_FLOAT16,
)

DEFAULT_FRAME_SAMPLE_COUNT = 25
DEFAULT_IMAGE_SIZE = 224
DEFAULT_BINARY_THRESHOLD = 0.5

DEFAULT_SPLITS_DIR = PROJECT_ROOT / "data" / "processed" / "splits"
DEFAULT_MANIFESTS_DIR = PROJECT_ROOT / "data" / "processed" / "manifests"
DEFAULT_MANIFESTS_BY_SPLIT_DIR = DEFAULT_MANIFESTS_DIR / "by_split"
DEFAULT_CALIBRATION_DIR = PROJECT_ROOT / "data" / "processed" / "calibration"
